### ISSUE TITLE
大佬能做个合集吗

### ISSUE THREAD

**Issue by Au3C2** [1204244136/index-X#2]
大佬能做个合集吗，一本一本分开看挺麻烦的呀

**Comment by 1204244136** [comment]
我这文件平均一个要8M，22本下来差不多就是176M……真的有人会看一本176M的电子书吗……
而且做合集因为代码和目录上的关系，也比较麻烦
一本书平均认真看下来要5个小时吧，一本一本看反而会有一种阶段感（
要说合集，别人做的也是有的，贴吧置顶就有

**Comment by Au3C2** [comment]
没事没事，我自己做了一个，谢谢你。这样kindle书架比较简洁
