### ISSUE TITLE
本篇部分新约epub混入了旧约中

### ISSUE THREAD

**Issue by MineTestGaming** [1204244136/index-X#3]
如题，旧约中混入了新约11-17卷的epub

**Comment by 1204244136** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "1204244136/index-X"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 晚上8:33
收件人:&nbsp;"1204244136/index-X"<index-X@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[1204244136/index-X] 本篇部分新约epub混入了旧约中 (#3)





 
如题
