### ISSUE TITLE
推荐Calibre作为PC端阅读器

### ISSUE THREAD

**Issue by GFDGIT** [1204244136/index-X#4]
Calibre是一个开源免费的图书管理软件，附赠阅读功能（不支持PDF）和编辑功能，可以完美支持epub的各种特性，弹注、跳转、各种字体特性、动画、多媒体等。阅读界面虽说稍显简陋，但也简单易上手，功能够用，高亮、书签都有，高手也可以自定义CSS等。

**Comment by 1204244136** [comment]
已添加，如有后续想法，希望能加群详谈
