### ISSUE TITLE
epub推荐用那些阅读器阅读呢 

### ISSUE THREAD

**Issue by toaruZhang** [1204244136/index-X#7]
手机上我记得微信读书支持epub，电脑端有什么好一点的软件吗？

**Comment by 1204244136** [comment]
主页有阅读器测评

**Comment by MapleCatalpa** [comment]
> 主页有阅读器测评

希望作者能够测评一下Sumatra PDF(https://github.com/sumatrapdfreader/sumatrapdf )，谢谢！

**Comment by 1204244136** [comment]
> > 主页有阅读器测评
> 
> 希望作者能够测评一下Sumatra PDF(https://github.com/sumatrapdfreader/sumatrapdf )，谢谢！

测评完了，不太行，如有后续建议希望能加群详谈，谢谢！
