### ISSUE TITLE
一个做在线阅读站的想法

### ISSUE THREAD

**Issue by misaka-fans** [1204244136/index-X#9]
hey，
看这仓库一年多没交commit了，希望大大还能回来看看这条issue，感激不尽！
我和一些朋友做了一个御坂美琴粉丝站（和魔禁wiki，星之相位等团队无关，个人项目），想在里面加一个在线阅读某系列小说的功能。看到您的收集很全。所以想问问你能不能把这些资源搬到我们的站搞个在线阅读？毕竟epub本质上也就是h5（doge

**Comment by 1204244136** [comment]
非常感谢你对我的电子书的认可。我很荣幸你想把它们分享到你的个人网站上，但是恐怕不行。因为这些电子书涉及到版权问题，在线阅读对我个人而言有点越线了。我只是出于个人爱好和学习目的制作整理的，不想给自己或者别人带来任何麻烦。
另外，仓库一年多没交commit是因为我把X系列的制作主题从github转移到了qq群，这样反馈与更新更方便。

**Comment by misaka-fans** [comment]
了解了，谢谢😘
